apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: default
data:
  config.yaml: |
    receivers:
      filelog/ingress:
        include:
          - /var/log/pods/ingress-nginx_ingress-nginx-controller-*/*/*.log
        start_at: beginning
        include_file_path: true

      hostmetrics:
        collection_interval: 30s
        root_path: /hostfs
        scrapers:
          cpu:
          memory:
          disk:
          network:
          load:
          filesystem:

      prometheus:
        config:
          scrape_configs:
            - job_name: nginx-ingress
              scrape_interval: 10s
              static_configs:
                - targets: ['10.43.194.82:10254']

      # Accept traces from ingress controller
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        timeout: 5s
      resource/tag:
        attributes:
          - key: service.name
            value: nginx-argocd-app
            action: upsert
          - key: deployment.environment
            value: production
            action: upsert

    exporters:
      otlp:
        endpoint: "192.168.1.128:32189"
        tls:
          insecure: true

    service:
      pipelines:
        logs:
          receivers: [filelog/ingress]
          processors: [batch, resource/tag]
          exporters: [otlp]
        metrics:
          receivers: [hostmetrics, prometheus]
          processors: [batch, resource/tag]
          exporters: [otlp]
        traces:
          receivers: [otlp]
          processors: [batch, resource/tag]
          exporters: [otlp]
