replicaCount: 1

image:
  repository: 10.0.2.15:8080/library/nginx-app
  tag: "1616987cf396c0283b21d543be3b1aa21fbe4344"
  pullPolicy: Always

imagePullSecrets:
  - name: harbor-secret

service:
  type: NodePort
  port: 80

ingress:
  enabled: false
