replicaCount: 1

image:
  repository: 10.0.2.15:8080/library/nginx-app
  tag: "2963263be605b409b2b88c98e0953e0602e373da"
  pullPolicy: Always

imagePullSecrets:
  - name: harbor-secret

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
