replicaCount: 1

image:
  repository: 10.0.2.15:8080/library/nginx-app
  tag: "9d18663e7f74bbc367fa38b2e98c646c6896e6d6"
  pullPolicy: Always

imagePullSecrets:
  - name: harbor-secret

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true

# Add to your existing values.yaml
signoz:
  enabled: true
  endpoint: "192.168.1.128:32189"   # e.g. 10.0.0.5:4317
  serviceName: nginx-argocd-app
  environment: production
